const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const values=new Map(), requests=[];
const rows=[{id:'Playgrounds/1',osmid:'way/1',created_at:'2026-09-24 05:03:29',updated_at:'2026-09-24 05:03:29',latitude:34.8,longitude:135.6,updated_by_userid:'saka'},
{id:'Playgrounds/2',osmid:'node/2',created_at:'2026-09-03 00:00:00',updated_at:'2026-09-24 05:03:29',latitude:null,longitude:null}];
const context={Date,URL,console,location:{href:'https://example.test/'},Conf:{etc:{localSave:'playgrounds'}},
poiStatusCont:{getAllFavorite:()=>[['playgrounds.node/2',{}]]},turf:{bbox:()=>[135,34,136,35],point:x=>x,booleanPointInPolygon:()=>true},window:{}};
vm.createContext(context);vm.runInContext(fs.readFileSync('lib/changecontroller.js','utf8')+'\nthis.Controller=ChangeController;',context);
const storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};
let oldApi=false;
const fetch=async url=>{requests.push(new URL(url));return {ok:true,json:async()=>oldApi?[{...rows[0],body:'full body'}]:new URL(url).searchParams.has('osmids')?rows.filter(row=>row.osmid==='node/2'):rows};};
const make=()=>{const c=new context.Controller({reviews:{use:true}}, {storage,fetch,now:()=>new Date('2026-10-05T00:00:00Z')});c.region=async()=>({name:'大阪府',feature:{}});return c;};
(async()=>{
const c=make();c.results=[{kind:'regionalCreated',item:{name:'OSM'}}];await c.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'});
assert.equal(c.results.length,3);assert.equal(requests.length,2);
assert.equal(requests[0].searchParams.get('summary'),'1');assert.equal(requests[0].searchParams.get('limit'),'30');assert(requests[0].searchParams.has('updated_since'));
assert.equal(c.results[1].kind,'reviewCreated');assert.equal(c.results[2].kind,'reviewUpdated');assert.equal(c.results[2].region.name,'お気に入り');
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/1').editorName,'saka');
const cached=make();await cached.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'});assert.equal(requests.length,2);assert.equal(cached.results.length,2);
await cached.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'}, {force:true});
assert.equal(requests.length,4);assert.equal(cached.results.length,2);
const saved=JSON.parse(values.get('cmapmaker-changes.review-results'));saved.fetchedAt-=11*60*1000;
values.set('cmapmaker-changes.review-results',JSON.stringify(saved));
await cached.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'});
assert.equal(requests.length,6);assert.equal(cached.results.length,2);
cached.region=async()=>({name:'兵庫県',code:'28',feature:{}});
context.turf.booleanPointInPolygon=()=>false;
await cached.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'});
assert.equal(requests.length,8);
assert.equal(cached.results.length,1);
assert.equal(cached.results[0].region.name,'お気に入り');
assert.equal(JSON.parse(values.get('cmapmaker-changes.review-results')).regionKey,'28');
// The new region's cached results must be reusable without additional requests.
await cached.checkActivityChanges({authMode:'basic',url:'https://example.test/api?app=playgrounds'});
assert.equal(requests.length,8);
assert.equal(cached.results.length,1);
assert.equal(cached.results[0].item.osmid,'node/2');
assert(!cached.results.some(result=>result.region.name==='大阪府'));
context.turf.booleanPointInPolygon=()=>true;
oldApi=true;const failed=make();failed.results=[{kind:'OSM'}];await failed.checkActivityChanges({authMode:'basic',url:'https://old.test/api'});assert.equal(failed.results.length,1);
const names=make();names.config.apiUrl='https://osm.test/api';
let nameRequests=0,overpassCalls=0;
context.poiCont={get_osmid:()=>undefined,pdata:{geojson:[{id:'way/1',properties:{name:'十三東公園'}}]},lnglats:{'way/1':[135.4,34.7]}};
names.query=async()=>{nameRequests++;throw new Error('Unexpected name request');};
context.overPassCont={getOsmIds:async(ids,c,bounds,options)=>{overpassCalls++;assert.equal(ids.join(','),'node/2');assert.equal(options.retry,false);return {geojson:[]};}};
const unnamed=rows.map(row=>({item:{osmid:row.osmid,name:'口コミのある公園・遊具'}}));
await names.resolveReviewNames(unnamed);
assert.equal(unnamed[0].item.name,'十三東公園');
assert.equal(unnamed[1].item.name,'公園・遊具の口コミ');
await names.resolveReviewNames(unnamed);
assert.equal(nameRequests,0);assert.equal(overpassCalls,1);
let batchCalls=0;
context.overPassCont={getOsmIds:async(ids,c,bounds,options)=>{
    batchCalls++;assert.equal(ids.join(','),'node/10,node/11');assert.equal(bounds.length,4);assert.equal(options.retry,false);
    await new Promise(resolve=>setTimeout(resolve,5));
    return {geojson:ids.map(id=>({id,properties:{name:'公園 '+id}}))};
}};
const batch=()=>['node/10','node/11','node/10'].map(osmid=>({item:{osmid,lon:135.5,lat:34.7}}));
const first=batch(), second=batch();
await Promise.all([names.resolveReviewNames(first),names.resolveReviewNames(second)]);
assert.equal(batchCalls,1);assert.equal(first[0].item.name,'公園 node/10');assert.equal(second[0].item.name,'公園 node/10');
await names.resolveReviewNames(batch());assert.equal(batchCalls,1);
const reloaded=make();await reloaded.resolveReviewNames(batch());assert.equal(batchCalls,1);
context.poiCont.adata=[{id:'Playgrounds/1',title:'<b>遊びやすい公園</b>',body:'あ'.repeat(81),score:'act_score_6',picture_url1:'File:park.jpg'},
{id:'unrelated',title:'別の口コミ',body:'違う本文'}];
c.results[1].item.activityId='Playgrounds/1';
const enriched=c.tickerItems().find(item=>item.activityId==='Playgrounds/1');
assert.equal(enriched.review.title,'遊びやすい公園');assert.equal(enriched.review.excerpt,'あ'.repeat(80)+'…');
assert.equal(enriched.review.score,5);assert.equal(enriched.review.hasPhoto,true);
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/2').review,null);
context.poiCont.adata[0].score='act_score_1';
context.poiCont.adata[0].updated_by_username='review_editor';
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/1').editorName,'review_editor');
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/1').review.score,null);
const review=c.results.find(result=>result.item.activityId==='Playgrounds/2');
review.item.name='公園・遊具（node/2）';
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/2').name,'公園・遊具の口コミ');
context.poiCont.get_parent=id=>id==='node/2'?{properties:{name:'丸山公園'}}:undefined;
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/2').name,'丸山公園');
context.areaFeatureLinker={getAreaRecord:id=>id==='way/1'?{feature:{properties:{name:'遊具のある公園'}}}:null};
assert.equal(c.tickerItems().find(item=>item.activityId==='Playgrounds/1').parkName,'遊具のある公園');
console.log('PASS: summary filters, regional/favorite deduplication, daily cache, and independent failure');
})().catch(e=>{console.error(e);process.exitCode=1;});
